language: node_js
dist: trusty
sudo: required
node_js:
  - "8"
git:
  depth: 50

branches:
  only:
  - master

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - ./node_modules/protractor/bin/webdriver-manager update --gecko=false

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start

jobs:
    include:
        - stage: "Protractor tests"
          script:
          - npm run build:plugin
          - ./node_modules/protractor/bin/protractor ./e2e/protractor.conf.ts || exit 1

cache:
  directories:
  - node_modules
  - .protractor-smartrunner
