version: ~> 1.0
language: node_js
dist: bionic
arch: arm64-graviton2
node_js:
  - 14.15.4

git:
  depth: 50

branches:
  only:
    - master
    - next

addons:
  chrome: stable
services:
  - xvfb

jobs:
  include:
    - stage: Run tests
      before_script: npm run build:plugin
      script: npm run ci
      if: type == pull_request
