language: node_js
dist: trusty
sudo: required
node_js:
  - "10"
git:
  depth: 50

branches:
  only:
  - master
  - next

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start

jobs:
    include:
        - stage: "Protractor tests"
          script: npm run ci

cache:
  directories:
  - node_modules
